spring:
 #mvc:
  #view:
   #prefix : /WEB-INF/
   #suffix : .html
 thymeleaf:
    prefix: classpath:/templates/
 datasource:
    url: jdbc:mysql://localhost:3306/dcsys_project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1q2w3e4r

server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true
#mybatis-plus:
 # configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


file:

   uploadFolder: C:\\uploadFiles\\
   tempFolder: C:\\tempFolder\\





logging:
   level:
      com.troila.mapper: DEBUG

