spring:
 #mvc:
  #view:
   #prefix : /WEB-INF/
   #suffix : .html
  data:
    mongodb:
      host: 8.210.11.103:27017
      port: 27017
      username: capstone
      password: casptone2020
      database: NSWBusinessDB


  thymeleaf:
    prefix: classpath:/templates/
    cache: false

server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true
#mybatis-plus:
 # configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


file:

   uploadFolder: C:\\uploadFiles\\
   tempFolder: C:\\tempFolder\\





logging:
   level:
      com.troila.mapper: DEBUG

